name: Deploy to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'vue.config.js'
      - 'tools/afterBuild.js'
      - '.github/workflows/pages-deploy.yml'

jobs:
  build-and-deploy:
    if: "!contains(toJSON(github.event.commits.*.message), '--skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
        env:
          VUE_APP_SHA: ${{ github.sha }}
          VUE_APP_HTTPS: ${{ secrets.HTTPS }}
          VUE_APP_GTAG: ${{ secrets.GTAG }}
          VUE_APP_CDN: ${{ secrets.CDN }}
          USE_CDN: ${{ secrets.USE_CDN }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIT_CONFIG_NAME: クロージャ
          GIT_CONFIG_EMAIL: closure@rhodes.island
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          SINGLE_COMMIT: true
