name: Deploy to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'vue.config.js'
      - 'tools/buildCDN.js'
      - '.github/workflows/pages-deploy.yml'
    tags:
      - 'deploy'
jobs:
  build-and-deploy:
    if: "!contains(toJSON(github.event.commits.*.message), '--skip-ci')"
    runs-on: ubuntu-latest
    env:
      VUE_APP_SHA: ${{ github.sha }}
      VUE_APP_HTTPS: ${{ secrets.HTTPS }}
      VUE_APP_GTAG: ${{ secrets.GTAG }}
      VUE_APP_CDN: ${{ secrets.CDN }}
      USE_CDN: ${{ secrets.USE_CDN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIT_CONFIG_NAME: クロージャ
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          SINGLE_COMMIT: true
