name: Deploy to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'vue.config.js'
      - 'tools/buildCDN.js'
      - '.github/workflows/**'
    tags:
      - 'deploy'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VUE_APP_HTTPS: ${{ secrets.HTTPS }}
      VUE_APP_GTAG: ${{ secrets.GTAG }}
      VUE_APP_CDN: ${{ secrets.CDN }}
      USE_CDN: ${{ secrets.USE_CDN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CNAME: ${{ secrets.CNAME }}
          BUILD_SCRIPT: yarn install --frozen-lockfile && yarn run build
